---
driver:
  name: vagrant

provisioner:
  name: salt_solo
  is_file_root: true
  pillars:
    top.sls:
      base:
        '*':
          - threatstack
    threatstack.sls:
      deploy_key: <%= ENV['TS_DEPLOY_KEY'] != nil ? ENV['TS_DEPLOY_KEY'] : 'ts_deploy_key' %>
      ts_agent_version: <%= ENV['TS_PACKAGE_VERSION'] %>
      <% if ENV['TS_CONFIG_ARGS'] %>
      ts_agent_config_args: <%= ENV['TS_CONFIG_ARGS'] %>
      <% end %>
      ts_agent_version: <%= ENV['TS_PACKAGE_VERSION'] %>
  state_top:
    base:
      '*':
        - threatstack

platforms:
  - name: centos-6.10
  - name: centos-7.6
  - name: debian-8.11
  - name: debian-9.6
  - name: ubuntu-16.04
  - name: ubuntu-18.04

suites:
  - name: default
